// <auto-generated />
using System;
using IIS_Projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IISProjekat.Migrations
{
    [DbContext(typeof(IIS_DBContext))]
    [Migration("20230524215758_RemovedIsConfirmedFlagFromFoodSupplyReport")]
    partial class RemovedIsConfirmedFlagFromFoodSupplyReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergyFood", b =>
                {
                    b.Property<long>("AllergiesId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.HasKey("AllergiesId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("AllergyFood");
                });

            modelBuilder.Entity("AllergyMedicalRecord", b =>
                {
                    b.Property<long>("AllergiesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicalRecordsId")
                        .HasColumnType("bigint");

                    b.HasKey("AllergiesId", "MedicalRecordsId");

                    b.HasIndex("MedicalRecordsId");

                    b.ToTable("AllergyMedicalRecord");
                });

            modelBuilder.Entity("DiagnosisMedicalRecord", b =>
                {
                    b.Property<long>("DiagnosesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicalRecordsId")
                        .HasColumnType("bigint");

                    b.HasKey("DiagnosesId", "MedicalRecordsId");

                    b.HasIndex("MedicalRecordsId");

                    b.ToTable("DiagnosisMedicalRecord");
                });

            modelBuilder.Entity("ExerciseTherapy", b =>
                {
                    b.Property<long>("RecommendedExercisesId")
                        .HasColumnType("bigint");

                    b.Property<long>("TherapyId")
                        .HasColumnType("bigint");

                    b.HasKey("RecommendedExercisesId", "TherapyId");

                    b.HasIndex("TherapyId");

                    b.ToTable("ExerciseTherapy");
                });

            modelBuilder.Entity("FoodOrderFoodSupplyReport", b =>
                {
                    b.Property<long>("FoodOrdersId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodSupplyReportId")
                        .HasColumnType("bigint");

                    b.HasKey("FoodOrdersId", "FoodSupplyReportId");

                    b.HasIndex("FoodSupplyReportId");

                    b.ToTable("FoodOrderFoodSupplyReport");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Allergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Beginning")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Ending")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Diagnosis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHypertrophic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryMuscleGroup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MuscleGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseTrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("int");

                    b.Property<string>("RepetitionRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainingSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("ExerciseTrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Food", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodPriceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FoodPriceId");

                    b.ToTable("FoodOrders");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodPrices");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<float>("Share")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FoodShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodSupplyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FoodSupplyReports");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Injury", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MuscleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("IIS_Projekat.Models.InjuryTherapy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InjuryId")
                        .HasColumnType("bigint");

                    b.Property<string>("InjurySeverity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TherapyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InjuryId");

                    b.HasIndex("TherapyId");

                    b.ToTable("InjuryTherapy");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("NutritionPlanId")
                        .HasColumnType("bigint");

                    b.Property<float>("PortionSize")
                        .HasColumnType("real");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NutritionPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Anamnesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Therapy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3159),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3159),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3221),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3221),
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3223),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3224),
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3225),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3226),
                            Name = "Abductors"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3227),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3227),
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3230),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3230),
                            Name = "Gluteus"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3231),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3231),
                            Name = "Core"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3233),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3233),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3234),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3235),
                            Name = "Lower Back"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3236),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3237),
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3238),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3238),
                            Name = "Teres Major"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3239),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3240),
                            Name = "Lower Traps"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3241),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3241),
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3242),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3243),
                            Name = "Rear Delts"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3248),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3248),
                            Name = "Side Delts"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3250),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3250),
                            Name = "Front Delts"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3251),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3252),
                            Name = "Upper Chest"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3253),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3254),
                            Name = "Lower Chest"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3255),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3255),
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3257),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3257),
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3258),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3258),
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3261),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(3261),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.Nutrient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8187),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8190),
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8217),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8217),
                            Name = "Fat"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8219),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8220),
                            Name = "Carbohydrates"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8222),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8222),
                            Name = "Fiber"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8224),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8224),
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8232),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8232),
                            Name = "Vitamin A"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8238),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(8239),
                            Name = "Vitamin B1"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9009),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9011),
                            Name = "Vitamin B2"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9015),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9015),
                            Name = "Vitamin B3"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9027),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9027),
                            Name = "Vitamin C"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9030),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9030),
                            Name = "Vitamin D"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9032),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9032),
                            Name = "Vitamin E"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9035),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9035),
                            Name = "Calcium"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9037),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9037),
                            Name = "Iron"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9039),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9039),
                            Name = "Magnesium"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9041),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9041),
                            Name = "Potassium"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9043),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9043),
                            Name = "Sodium"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9045),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 136, DateTimeKind.Utc).AddTicks(9045),
                            Name = "Zinc"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutrientShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("NutrientId")
                        .HasColumnType("bigint");

                    b.Property<float>("Share")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("NutrientId");

                    b.ToTable("NutrientShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutritionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Therapy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MedicalRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlanRequests");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainingPlanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(594),
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 24, 21, 57, 58, 135, DateTimeKind.Utc).AddTicks(597),
                            Password = "7EC7F49F580E02ECA097C2F6E26C84D788911717C9592D8194AC3E6E58295A9059B7D79298897DD3B4EC6CB81888B59DE2AEF8813427B1D9B7F7EF5D2BADCAB5",
                            Role = "ADMIN",
                            Salt = new byte[] { 241, 229, 249, 92, 52, 46, 19, 241, 204, 188, 136, 187, 240, 159, 243, 129, 190, 156, 25, 65, 92, 153, 222, 212, 142, 101, 240, 171, 214, 223, 96, 221, 192, 169, 195, 33, 104, 136, 119, 151, 88, 224, 190, 30, 108, 59, 181, 23, 35, 18, 61, 108, 143, 187, 182, 57, 35, 201, 59, 136, 96, 212, 94, 207 }
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AllergyFood", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllergyMedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MedicalRecord", null)
                        .WithMany()
                        .HasForeignKey("MedicalRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiagnosisMedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MedicalRecord", null)
                        .WithMany()
                        .HasForeignKey("MedicalRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseTherapy", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("RecommendedExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Therapy", null)
                        .WithMany()
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodOrderFoodSupplyReport", b =>
                {
                    b.HasOne("IIS_Projekat.Models.FoodOrder", null)
                        .WithMany()
                        .HasForeignKey("FoodOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.FoodSupplyReport", null)
                        .WithMany()
                        .HasForeignKey("FoodSupplyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIS_Projekat.Models.Appointment", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("ExercisesMG")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseTrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("ExercisesTS")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.TrainingSession", "TrainingSession")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodOrder", b =>
                {
                    b.HasOne("IIS_Projekat.Models.FoodPrice", "FoodPrice")
                        .WithMany()
                        .HasForeignKey("FoodPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodPrice");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodPrice", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodShare", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany("Participations")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Recipe", "Recipe")
                        .WithMany("FoodShares")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Injury", b =>
                {
                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "Muscle")
                        .WithMany("Injuries")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("IIS_Projekat.Models.InjuryTherapy", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Injury", "Injury")
                        .WithMany("Injuries")
                        .HasForeignKey("InjuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Therapy", "Therapy")
                        .WithMany("Therapies")
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Injury");

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Meal", b =>
                {
                    b.HasOne("IIS_Projekat.Models.NutritionPlan", "NutritionPlan")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutritionPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("IIS_Projekat.Models.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutrientShare", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany("NutrientShares")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Nutrient", "Nutrient")
                        .WithMany("Participations")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutritionPlan", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Therapy", b =>
                {
                    b.HasOne("IIS_Projekat.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Therapies")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("IIS_Projekat.Models.UsersProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Navigation("ExercisesMG");

                    b.Navigation("ExercisesTS");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Food", b =>
                {
                    b.Navigation("NutrientShares");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Injury", b =>
                {
                    b.Navigation("Injuries");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.Navigation("Therapies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Navigation("Injuries");

                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Nutrient", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutritionPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Recipe", b =>
                {
                    b.Navigation("FoodShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Therapy", b =>
                {
                    b.Navigation("Therapies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
