// <auto-generated />
using System;
using IIS_Projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IISProjekat.Migrations
{
    [DbContext(typeof(IIS_DBContext))]
    [Migration("20230719103227_AddedMedicalRecordToMeasurement")]
    partial class AddedMedicalRecordToMeasurement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergyFood", b =>
                {
                    b.Property<long>("AllergiesId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.HasKey("AllergiesId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("AllergyFood");
                });

            modelBuilder.Entity("AllergyMedicalRecord", b =>
                {
                    b.Property<long>("AllergiesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicalRecordsId")
                        .HasColumnType("bigint");

                    b.HasKey("AllergiesId", "MedicalRecordsId");

                    b.HasIndex("MedicalRecordsId");

                    b.ToTable("AllergyMedicalRecord");
                });

            modelBuilder.Entity("DiagnosisMedicalRecord", b =>
                {
                    b.Property<long>("DiagnosesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicalRecordsId")
                        .HasColumnType("bigint");

                    b.HasKey("DiagnosesId", "MedicalRecordsId");

                    b.HasIndex("MedicalRecordsId");

                    b.ToTable("DiagnosisMedicalRecord");
                });

            modelBuilder.Entity("ExerciseTherapy", b =>
                {
                    b.Property<long>("RecommendedExercisesId")
                        .HasColumnType("bigint");

                    b.Property<long>("TherapyId")
                        .HasColumnType("bigint");

                    b.HasKey("RecommendedExercisesId", "TherapyId");

                    b.HasIndex("TherapyId");

                    b.ToTable("ExerciseTherapy");
                });

            modelBuilder.Entity("FoodOrderFoodSupplyReport", b =>
                {
                    b.Property<long>("FoodOrdersId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodSupplyReportId")
                        .HasColumnType("bigint");

                    b.HasKey("FoodOrdersId", "FoodSupplyReportId");

                    b.HasIndex("FoodSupplyReportId");

                    b.ToTable("FoodOrderFoodSupplyReport");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Allergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Beginning")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Ending")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Diagnosis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHypertrophic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryMuscleGroup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MuscleGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseTrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnhappy")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("int");

                    b.Property<string>("RepetitionRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainingSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("ExerciseTrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Food", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodPriceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FoodPriceId");

                    b.ToTable("FoodOrders");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodPrices");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<float>("Share")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FoodShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodSupplyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FoodSupplyReports");
                });

            modelBuilder.Entity("IIS_Projekat.Models.InjuredMuscleTherapy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InjuredMuscleId")
                        .HasColumnType("bigint");

                    b.Property<string>("InjurySeverity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TherapyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InjuredMuscleId");

                    b.HasIndex("TherapyId");

                    b.ToTable("InjuredMuscleTherapy");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("NutritionPlanId")
                        .HasColumnType("bigint");

                    b.Property<float>("PortionSize")
                        .HasColumnType("real");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NutritionPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("Bicep")
                        .HasColumnType("real");

                    b.Property<float>("Calf")
                        .HasColumnType("real");

                    b.Property<float>("Chest")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Forearm")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MedicalRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Thigh")
                        .HasColumnType("real");

                    b.Property<float>("Waist")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Anamnesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Therapy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8405),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8407),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8430),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8430),
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8432),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8433),
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8434),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8435),
                            Name = "Abductors"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8437),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8437),
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8440),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8440),
                            Name = "Gluteus"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8442),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8442),
                            Name = "Core"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8444),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8444),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8446),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8447),
                            Name = "Lower Back"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8449),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8449),
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8451),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8451),
                            Name = "Teres Major"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8453),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8454),
                            Name = "Lower Traps"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8455),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8455),
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8457),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8457),
                            Name = "Rear Delts"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8467),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8468),
                            Name = "Side Delts"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8469),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8470),
                            Name = "Front Delts"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8471),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8472),
                            Name = "Upper Chest"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8474),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8475),
                            Name = "Lower Chest"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8476),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8476),
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8478),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8478),
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8480),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8480),
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8494),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(8494),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.Nutrient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4752),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4754),
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4772),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4772),
                            Name = "Fat"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4775),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4775),
                            Name = "Carbohydrates"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4777),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4777),
                            Name = "Fiber"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4779),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4779),
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4782),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4782),
                            Name = "Vitamin A"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4784),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4784),
                            Name = "Vitamin B1"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4812),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4812),
                            Name = "Vitamin B2"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4814),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4814),
                            Name = "Vitamin B3"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4817),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4817),
                            Name = "Vitamin C"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4818),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4819),
                            Name = "Vitamin D"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4821),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4822),
                            Name = "Vitamin E"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4823),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4824),
                            Name = "Calcium"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4825),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4825),
                            Name = "Iron"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4827),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4827),
                            Name = "Magnesium"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4829),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4829),
                            Name = "Potassium"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4831),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4831),
                            Name = "Sodium"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4834),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 49, DateTimeKind.Utc).AddTicks(4834),
                            Name = "Zinc"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutrientShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("NutrientId")
                        .HasColumnType("bigint");

                    b.Property<float>("Share")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("NutrientId");

                    b.ToTable("NutrientShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutritionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Therapy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MedicalRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("Therapies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlanRequests");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainingPlanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(5039),
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 19, 10, 32, 27, 47, DateTimeKind.Utc).AddTicks(5042),
                            Password = "F721CE189853D26B6F1F3AB7E80B81F7C69FC02A482A52ABF366DBDCB6CF73F95201FD2E228B28DF1D5627CB82E252C70E0455ACD4A1CD38AA2BED2007AE7583",
                            Role = "ADMIN",
                            Salt = new byte[] { 81, 118, 17, 76, 51, 160, 15, 248, 174, 236, 222, 214, 25, 46, 37, 242, 108, 164, 49, 76, 30, 176, 24, 181, 91, 212, 89, 111, 85, 127, 126, 85, 190, 141, 38, 19, 7, 173, 89, 123, 52, 6, 172, 253, 69, 26, 216, 245, 69, 209, 69, 232, 94, 100, 73, 65, 34, 136, 6, 21, 229, 169, 243, 240 }
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AllergyFood", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllergyMedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MedicalRecord", null)
                        .WithMany()
                        .HasForeignKey("MedicalRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiagnosisMedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MedicalRecord", null)
                        .WithMany()
                        .HasForeignKey("MedicalRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseTherapy", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("RecommendedExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Therapy", null)
                        .WithMany()
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodOrderFoodSupplyReport", b =>
                {
                    b.HasOne("IIS_Projekat.Models.FoodOrder", null)
                        .WithMany()
                        .HasForeignKey("FoodOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.FoodSupplyReport", null)
                        .WithMany()
                        .HasForeignKey("FoodSupplyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIS_Projekat.Models.Appointment", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("TargetedByExercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseTrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.TrainingSession", "TrainingSession")
                        .WithMany("ExercisesInSession")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodOrder", b =>
                {
                    b.HasOne("IIS_Projekat.Models.FoodPrice", "FoodPrice")
                        .WithMany()
                        .HasForeignKey("FoodPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodPrice");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodPrice", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodShare", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany("Participations")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Recipe", "Recipe")
                        .WithMany("FoodShares")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("IIS_Projekat.Models.InjuredMuscleTherapy", b =>
                {
                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "InjuredMuscle")
                        .WithMany("TherapiesForInjury")
                        .HasForeignKey("InjuredMuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Therapy", "Therapy")
                        .WithMany("InjuredMuscles")
                        .HasForeignKey("TherapyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InjuredMuscle");

                    b.Navigation("Therapy");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Meal", b =>
                {
                    b.HasOne("IIS_Projekat.Models.NutritionPlan", "NutritionPlan")
                        .WithMany("Meals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutritionPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Measurement", b =>
                {
                    b.HasOne("IIS_Projekat.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Measurements")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("IIS_Projekat.Models.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutrientShare", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany("NutrientShares")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Nutrient", "Nutrient")
                        .WithMany("Participations")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutritionPlan", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Therapy", b =>
                {
                    b.HasOne("IIS_Projekat.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Therapies")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("IIS_Projekat.Models.UsersProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Navigation("MuscleGroups");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Food", b =>
                {
                    b.Navigation("NutrientShares");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Therapies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Navigation("TargetedByExercises");

                    b.Navigation("TherapiesForInjury");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Nutrient", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutritionPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Recipe", b =>
                {
                    b.Navigation("FoodShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Therapy", b =>
                {
                    b.Navigation("InjuredMuscles");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Navigation("ExercisesInSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
