// <auto-generated />
using System;
using IIS_Projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IISProjekat.Migrations
{
    [DbContext(typeof(IIS_DBContext))]
    [Migration("20230516172105_HeightAndWeightIntToFloatType")]
    partial class HeightAndWeightIntToFloatType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AllergyFood", b =>
                {
                    b.Property<long>("AllergiesId")
                        .HasColumnType("bigint");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.HasKey("AllergiesId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("AllergyFood");
                });

            modelBuilder.Entity("AllergyMedicalRecord", b =>
                {
                    b.Property<long>("AllergiesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicalRecordsId")
                        .HasColumnType("bigint");

                    b.HasKey("AllergiesId", "MedicalRecordsId");

                    b.HasIndex("MedicalRecordsId");

                    b.ToTable("AllergyMedicalRecord");
                });

            modelBuilder.Entity("DiagnosisMedicalRecord", b =>
                {
                    b.Property<long>("DiagnosesId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicalRecordsId")
                        .HasColumnType("bigint");

                    b.HasKey("DiagnosesId", "MedicalRecordsId");

                    b.HasIndex("MedicalRecordsId");

                    b.ToTable("DiagnosisMedicalRecord");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Allergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Beginning")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Ending")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Diagnosis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHypertrophic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryMuscleGroup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MuscleGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseTrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("int");

                    b.Property<string>("RepetitionRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainingSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("ExerciseTrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Food", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Share")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FoodShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Injury", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MuscleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MuscleId");

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("IIS_Projekat.Models.InjuryMedicalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InjuryId")
                        .HasColumnType("bigint");

                    b.Property<string>("InjurySeverity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MedicalRecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InjuryId");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("InjuryMedicalRecord");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Anamnesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Therapy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2791),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2792),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2806),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2806),
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2809),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2809),
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2811),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2811),
                            Name = "Abductors"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2812),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2813),
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2815),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2816),
                            Name = "Gluteus"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2817),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2817),
                            Name = "Core"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2820),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2820),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2822),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2822),
                            Name = "Lower Back"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2824),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2825),
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2826),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2827),
                            Name = "Teres Major"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2828),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2829),
                            Name = "Lower Traps"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2831),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2831),
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2832),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2833),
                            Name = "Rear Delts"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2846),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2847),
                            Name = "Side Delts"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2848),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2849),
                            Name = "Front Delts"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2850),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2850),
                            Name = "Upper Chest"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2853),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2853),
                            Name = "Lower Chest"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2854),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2855),
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2856),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2856),
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2858),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2858),
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2860),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(2860),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.Nutrient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5109),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5110),
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5120),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5120),
                            Name = "Fat"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5122),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5123),
                            Name = "Carbohydrates"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5124),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5125),
                            Name = "Fiber"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5126),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5126),
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5129),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5129),
                            Name = "Vitamin A"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5131),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5131),
                            Name = "Vitamin B1"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5161),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5161),
                            Name = "Vitamin B2"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5163),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5163),
                            Name = "Vitamin B3"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5165),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5165),
                            Name = "Vitamin C"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5167),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5167),
                            Name = "Vitamin D"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5169),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5169),
                            Name = "Vitamin E"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5170),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5171),
                            Name = "Calcium"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5173),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5173),
                            Name = "Iron"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5174),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5175),
                            Name = "Magnesium"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5176),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5176),
                            Name = "Potassium"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5178),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5178),
                            Name = "Sodium"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5265),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 354, DateTimeKind.Utc).AddTicks(5265),
                            Name = "Zinc"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutrientShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FoodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("NutrientId")
                        .HasColumnType("bigint");

                    b.Property<int>("Share")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("NutrientId");

                    b.ToTable("NutrientShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlanRequests");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainingPlanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(521),
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 16, 17, 21, 5, 353, DateTimeKind.Utc).AddTicks(525),
                            Password = "5DD01DBC577FEBA9B41B6DE01CC40B5F7330F6E13E718A30EDD8BEE430ADF1DA492FEF02E822DB67EE1C93583101FAEB93F664A146BF0D66F43E600F6873A596",
                            Role = "ADMIN",
                            Salt = new byte[] { 129, 20, 245, 49, 211, 83, 164, 86, 149, 60, 120, 43, 93, 38, 13, 152, 136, 92, 28, 192, 97, 234, 98, 60, 164, 214, 173, 34, 147, 3, 127, 178, 160, 4, 182, 165, 26, 169, 110, 84, 133, 149, 192, 19, 212, 149, 210, 114, 189, 12, 14, 187, 214, 1, 107, 189, 94, 17, 176, 35, 182, 245, 1, 255 }
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AllergyFood", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllergyMedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MedicalRecord", null)
                        .WithMany()
                        .HasForeignKey("MedicalRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiagnosisMedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MedicalRecord", null)
                        .WithMany()
                        .HasForeignKey("MedicalRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIS_Projekat.Models.Appointment", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Report", "Report")
                        .WithOne("Appointment")
                        .HasForeignKey("IIS_Projekat.Models.Appointment", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("ExercisesMG")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseTrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("ExercisesTS")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.TrainingSession", "TrainingSession")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.FoodShare", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany("Participations")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Recipe", "Recipe")
                        .WithMany("FoodShares")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Injury", b =>
                {
                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "Muscle")
                        .WithMany("Injuries")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("IIS_Projekat.Models.InjuryMedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Injury", "Injury")
                        .WithMany("Injuries")
                        .HasForeignKey("InjuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Injury");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("IIS_Projekat.Models.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.NutrientShare", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Food", "Food")
                        .WithMany("NutrientShares")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.Nutrient", "Nutrient")
                        .WithMany("Participations")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("IIS_Projekat.Models.UsersProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Navigation("ExercisesMG");

                    b.Navigation("ExercisesTS");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Food", b =>
                {
                    b.Navigation("NutrientShares");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Injury", b =>
                {
                    b.Navigation("Injuries");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MedicalRecord", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Navigation("Injuries");

                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Nutrient", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Recipe", b =>
                {
                    b.Navigation("FoodShares");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Report", b =>
                {
                    b.Navigation("Appointment")
                        .IsRequired();
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
