// <auto-generated />
using System;
using IIS_Projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IISProjekat.Migrations
{
    [DbContext(typeof(IIS_DBContext))]
    [Migration("20230417105527_ClientTrainingPlanAndRequestRelationships")]
    partial class ClientTrainingPlanAndRequestRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseTrainingSession", b =>
                {
                    b.Property<long>("ExercisesId")
                        .HasColumnType("bigint");

                    b.Property<long>("TrainingSessionsId")
                        .HasColumnType("bigint");

                    b.HasKey("ExercisesId", "TrainingSessionsId");

                    b.HasIndex("TrainingSessionsId");

                    b.ToTable("ExerciseTrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repetitions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryMuscleGroup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MuscleGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7275),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7276),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7289),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7289),
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7291),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7291),
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7293),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7293),
                            Name = "Abductors"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7294),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7295),
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7297),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7297),
                            Name = "Gluteus"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7425),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7426),
                            Name = "Core"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7432),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7432),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7433),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7434),
                            Name = "Lower Back"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7436),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7436),
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7437),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7437),
                            Name = "Teres Major"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7439),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7439),
                            Name = "Lower Traps"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7440),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7441),
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7442),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7442),
                            Name = "Rear Delts"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7455),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7456),
                            Name = "Side Delts"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7458),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7458),
                            Name = "Front Delts"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7459),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7460),
                            Name = "Upper Chest"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7462),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7462),
                            Name = "Lower Chest"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7464),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7464),
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7466),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7466),
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7467),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7468),
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7469),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(7470),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlanRequests");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfExercises")
                        .HasColumnType("int");

                    b.Property<long>("TrainingPlanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(5360),
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 4, 17, 10, 55, 27, 245, DateTimeKind.Utc).AddTicks(5362),
                            Password = "178533E0CFDB492829F7718B75275C0EB1616BF01038A06811C2075BA048A0AFD12A47A25A465B2A70543278044428D58D9D38D0F5D2CDFF4DA1586493DC9337",
                            Role = "ADMIN",
                            Salt = new byte[] { 222, 197, 107, 65, 120, 86, 18, 222, 17, 136, 181, 85, 158, 117, 212, 91, 188, 81, 61, 110, 16, 206, 161, 107, 202, 186, 139, 105, 162, 188, 193, 4, 153, 229, 117, 164, 77, 44, 156, 244, 134, 195, 70, 108, 206, 242, 173, 212, 201, 195, 85, 200, 94, 199, 193, 84, 12, 46, 48, 35, 240, 0, 118, 32 }
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Avatar")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ExerciseTrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.TrainingSession", null)
                        .WithMany()
                        .HasForeignKey("TrainingSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("IIS_Projekat.Models.UsersProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
