// <auto-generated />
using System;
using IIS_Projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IISProjekat.Migrations
{
    [DbContext(typeof(IIS_DBContext))]
    [Migration("20230509092935_AddedHypertrophicCheckToExercise")]
    partial class AddedHypertrophicCheckToExercise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseTrainingSession", b =>
                {
                    b.Property<long>("ExercisesId")
                        .HasColumnType("bigint");

                    b.Property<long>("TrainingSessionsId")
                        .HasColumnType("bigint");

                    b.HasKey("ExercisesId", "TrainingSessionsId");

                    b.HasIndex("TrainingSessionsId");

                    b.ToTable("ExerciseTrainingSession");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHypertrophic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryMuscleGroup")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MuscleGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7934),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7935),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7946),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7947),
                            Name = "Quads"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7949),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7949),
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7951),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7951),
                            Name = "Abductors"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7952),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7953),
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7955),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7955),
                            Name = "Gluteus"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7957),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7957),
                            Name = "Core"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7959),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7959),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7961),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7961),
                            Name = "Lower Back"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7963),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7963),
                            Name = "Lats"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7964),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7965),
                            Name = "Teres Major"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7966),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7966),
                            Name = "Lower Traps"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7968),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7968),
                            Name = "Traps"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7970),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7970),
                            Name = "Rear Delts"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7977),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7977),
                            Name = "Side Delts"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7979),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7979),
                            Name = "Front Delts"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7981),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7981),
                            Name = "Upper Chest"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7984),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7984),
                            Name = "Lower Chest"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7986),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7986),
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7998),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(7998),
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(8000),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(8000),
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(8001),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(8002),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TrainingGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TrainingPlanRequests");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfExercises")
                        .HasColumnType("int");

                    b.Property<long>("TrainingPlanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(5954),
                            Email = "admin@gmail.com",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 5, 9, 9, 29, 35, 691, DateTimeKind.Utc).AddTicks(5957),
                            Password = "8F301F3F1E4DA991379E85E504C15EA8B591671C54889D396844F32460BDBA3FD6BC4AD1EDF43A2B7F589E1ACA80830AC0B18418BE65E6A39DD9BB43BE25B49F",
                            Role = "ADMIN",
                            Salt = new byte[] { 20, 43, 234, 119, 196, 24, 11, 103, 183, 201, 52, 120, 33, 115, 251, 88, 142, 241, 183, 46, 199, 168, 45, 133, 36, 103, 254, 61, 239, 246, 31, 106, 56, 192, 135, 6, 148, 202, 42, 59, 213, 59, 6, 118, 113, 140, 92, 148, 96, 21, 201, 237, 229, 19, 90, 119, 236, 200, 39, 152, 175, 89, 47, 170 }
                        });
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ExerciseTrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.TrainingSession", null)
                        .WithMany()
                        .HasForeignKey("TrainingSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IIS_Projekat.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("IIS_Projekat.Models.Exercise", "Exercise")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IIS_Projekat.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlanRequest", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingSession", b =>
                {
                    b.HasOne("IIS_Projekat.Models.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("IIS_Projekat.Models.UsersProfile", b =>
                {
                    b.HasOne("IIS_Projekat.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("IIS_Projekat.Models.UsersProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IIS_Projekat.Models.Exercise", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("IIS_Projekat.Models.MuscleGroup", b =>
                {
                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("IIS_Projekat.Models.TrainingPlan", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("IIS_Projekat.Models.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
